### ISSUE TITLE
Cannot read property '_runRegisterInterceptors' of undefined

### ISSUE THREAD

**Issue by RichardSlater** [RateGravity/netlify-webpack-plugin#10]
# Sample Configuration

```
const { NetlifyPlugin } = require("netlify-webpack-plugin");

module.exports = {
  plugins: [
    new NetlifyPlugin({}),
  ],
};
```

# Error

```
TypeError: Cannot read property '_runRegisterInterceptors' of undefined
    at tap (C:\source\richardslater\tlf-members-map\node_modules\tapable\lib\Hook.js:41:18)
    at NetlifyPlugin.apply (C:\source\richardslater\tlf-members-map\node_modules\netlify-webpack-plugin\dist\index.js:178:22)
    at webpack (C:\source\richardslater\tlf-members-map\node_modules\webpack\lib\webpack.js:51:13)
    at processOptions (C:\source\richardslater\tlf-members-map\node_modules\webpack-cli\bin\cli.js:272:16)
    at C:\source\richardslater\tlf-members-map\node_modules\webpack-cli\bin\cli.js:364:3
    at Object.parse (C:\source\richardslater\tlf-members-map\node_modules\yargs\yargs.js:567:18)
    at C:\source\richardslater\tlf-members-map\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\source\richardslater\tlf-members-map\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (C:\source\richardslater\tlf-members-map\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

# Environment

 - **node**: v14.3.0
 - **npm**: 6.14.4
 - **OS**: Windows 10.0.18363.0

**Comment by chris-pardy** [comment]
@RichardSlater Thanks for reporting this bug. I just released version 1.1.1 of neltify-webpack-plugin that should resolve your issue.
